repos:
  - repo: https://github.com/twisted/towncrier
    rev: 23.11.0  # run 'pre-commit autoupdate' to update
    hooks:
      - id: towncrier-update
        files: changelog.d/
        args: ['--keep', '--version', 'unreleased']
