repos:
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8
    hooks:
      - id: prettier
        args: ["--ignore-path=.prettierignore"]
  - repo: local
    hooks:
      - id: touch-foo-yaml
        name: Touch foo.yaml
        entry: touch foo.yaml
        language: system
        stages: [commit]
