name: Retry Action

on:
  issue_comment:
    types: [created]

jobs:
  retry_job:
    if: contains(github.event.comment.body, '/renovate') && github.event.comment.user.login == 'MaxWinterstein'
    runs-on: ubuntu-latest
    steps:
      - name: Add rocket emoji to comment
        run: |
          COMMENT_BODY=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }}/issues/comments/${{ github.event.comment.id }} | jq -r .body)
          NEW_BODY="${COMMENT_BODY} 🚀"
          curl -X PATCH \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            -d "{\"body\":\"${NEW_BODY}\"}" \
            https://api.github.com/repos/${{ github.repository }}/issues/comments/${{ github.event.comment.id }}
      - name: Checkout
        uses: actions/checkout@v4.2.0
      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v40.3.1
        with:
          token: ${{ secrets.RENOVATE_TOKEN }}
          configurationFile: .github/renovate.json


      - name: Delete the comment
        run: |
          curl -X DELETE \
          -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/${{ github.repository }}/issues/comments/${{ github.event.comment.id }}



# name: Renovate
# on:
#   pull_request:
#   schedule:
#     # The "*" (#42, asterisk) character has special semantics in YAML, so this
#     # string has to be quoted.
#     - cron: '0/15 * * * *'
#   workflow_dispatch:
# jobs:
#   renovate:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout
#         uses: actions/checkout@v4.2.0
#       - name: Self-hosted Renovate
#         uses: renovatebot/github-action@v40.3.1
#         with:
#           token: ${{ secrets.RENOVATE_TOKEN }}
#           configurationFile: .github/renovate.json
