name: Run renovate

on:
  issue_comment:
    types: [created]

jobs:
  run_from_schedule:

    steps:
      - &renovate_steps
        - name: Checkout
          uses: actions/checkout@v4.2.0

        - name: Self-hosted Renovate
          uses: renovatebot/github-action@v40.3.1
          with:
            token: ${{ secrets.RENOVATE_TOKEN }}
            configurationFile: .github/renovate.json

  run_from_comment:
    if: contains(github.event.comment.body, '/renovate') && github.event.comment.user.login == 'MaxWinterstein'
    runs-on: ubuntu-latest
    steps:
      - name: Add 🚀 reaction to comment
        run: |
          curl -X POST \
            -H "Authorization: token ${{ secrets.RENOVATE_ACTION }}" \
            -H "Accept: application/vnd.github.squirrel-girl-preview+json" \
            -d '{"content": "rocket"}' \
            https://api.github.com/repos/${{ github.repository }}/issues/comments/${{ github.event.comment.id }}/reactions


        env:
          RENOVATE_REPOSITORIES: "['${{ github.repository }}']"

      # First add checkmark comment as this is shown immediately, delete only after reload
      - name: Add ✅ reaction to comment
        run: |
          curl -X POST \
            -H "Authorization: token ${{ secrets.RENOVATE_ACTION }}" \
            -H "Accept: application/vnd.github.squirrel-girl-preview+json" \
            -d '{"content": "white_check_mark"}' \
            https://api.github.com/repos/${{ github.repository }}/issues/comments/${{ github.event.comment.id }}/reactions

      - *renovate_steps

      - name: Delete the comment
        run: |
          curl -X DELETE \
          -H "Authorization: token ${{ secrets.RENOVATE_ACTION }}" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/${{ github.repository }}/issues/comments/${{ github.event.comment.id }}



# name: Renovate
# on:
#   pull_request:
#   schedule:
#     # The "*" (#42, asterisk) character has special semantics in YAML, so this
#     # string has to be quoted.
#     - cron: '0/15 * * * *'
#   workflow_dispatch:
# jobs:
#   renovate:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout
#         uses: actions/checkout@v4.2.0
#       - name: Self-hosted Renovate
#         uses: renovatebot/github-action@v40.3.1
#         with:
#           token: ${{ secrets.RENOVATE_TOKEN }}
#           configurationFile: .github/renovate.json
