name: Run renovate

on:
  # push:
    # branches:
      # - main
  issue_comment:
    types: [created]
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  run renovate:
    if: github.event_name == 'schedule' || github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.0

      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v40.3.1
        with:
          token: ${{ secrets.RENOVATE_TOKEN }}
          configurationFile: .github/renovate.json
        env:
          RENOVATE_REPOSITORIES: "['${{ github.repository }}']"