name: Bump Version in config.yaml

on:
  pull_request:

jobs:
  bump-version:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Fetch all branches
        run: |
          git fetch --no-tags --prune --depth=1 origin +refs/heads/*:refs/remotes/origin/*
      # Install dependencies, like yq for manipulating YAML
      - name: Install yq
        run: sudo apt-get install -y jq python3-pip && pip3 install yq

      # Get list of changed files
      - name: Get list of changed files
        id: changed_files
        run: |
          git diff --name-only origin/main HEAD > changed_files.txt
          echo "foo"
          cat changed_files.txt
          echo "bar"
          echo "::set-output name=files::$(cat changed_files.txt)"

      # Find all the config.yaml files and check for changes in neighboring files
      - name: Find relevant config.yaml files
        id: check_config
        run: |
          find . -name "config.yaml"
          echo "find above"
          # Find all config.yaml files and check for changes next to or below them
          while IFS= read -r file; do
            dir=$(dirname "$file")
            echo  "if grep -q \"$dir\" changed_files.txt; then"
            if grep -q "$dir" changed_files.txt; then
              echo "Found changed file near $file"
              config_files+="$file "
            fi
          done < <(find . -name "config.yaml" | sed 's|^\./||')

          if [ -n "$config_files" ]; then
            echo "::set-output name=config_files::$config_files"
          fi

      # Bump version in config.yaml files
      - name: Bump version in config.yaml
        if: steps.check_config.outputs.config_files
        run: |
          for file in ${{ steps.check_config.outputs.config_files }}; do
            current_version=$(yq '.version' "$file")
            new_version=$(echo $current_version | awk -F. '{$NF+=1}1' | sed 's/ /./g')
            yq  -i ".version |= \"$new_version\"" "$file"
            echo "Bumped $file version from $current_version to $new_version"
          done

      # Commit the updated files
      - name: Commit changes
        if: steps.check_config.outputs.config_files
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git add ${{ steps.check_config.outputs.config_files }}
          git commit -m "Bump version in config.yaml files"
          git push
